// POST /functions/v1/create-property
// Hermes creates a property (from the outbound secretary's CSV), its owner contact and image rows.
// property_number is generated by the existing DB trigger — never supplied by Hermes.

import { guard, json, logEvent, normalizePhone, restGet, restPatch, restPost } from "../_shared/hermes.ts";

type Img = { image_url: string; is_front_image?: boolean; display_order?: number };

const str = (v: unknown, max = 500) =>
  typeof v === "string" && v.trim() ? v.trim().slice(0, max) : null;
const num = (v: unknown) => {
  const n = typeof v === "number" ? v : typeof v === "string" ? Number(v.replace(",", ".")) : NaN;
  return Number.isFinite(n) ? n : null;
};
const bool = (v: unknown) => (typeof v === "boolean" ? v : undefined);

Deno.serve(async (req) => {
  const g = guard(req, "POST");
  if (g instanceof Response) return g;
  const { key } = g;
  const requestId = req.headers.get("x-request-id");

  let body: any;
  try {
    body = JSON.parse((await req.text()) || "{}");
  } catch {
    return json({ error: "invalid json" }, 400);
  }

  const errors: string[] = [];
  const title = str(body.title, 250);
  const property_type = str(body.property_type, 100);
  const address = str(body.address, 300);
  const price = num(body.price);
  const area = num(body.area);

  if (!title) errors.push("title is required");
  if (!property_type) errors.push("property_type is required");
  if (!address) errors.push("address is required");
  if (price === null || price < 0) errors.push("price must be a non-negative number");
  if (area === null || area <= 0) errors.push("area must be a positive number");

  if (errors.length) {
    await logEvent({
      event_type: "property.create",
      status: "rejected",
      request_id: requestId,
      key_label: key.label,
      payload: body,
      error_message: errors.join("; "),
    });
    return json({ error: "validation failed", details: errors }, 400);
  }

  try {
    // Idempotency: skip if an identical listing was already imported.
    const dupeKey = str(body.external_id, 200);
    if (dupeKey) {
      const prior = await restGet(
        `/hermes_events?select=property_id,property_number&event_type=eq.property.create&status=eq.processed` +
          `&payload->>external_id=eq.${encodeURIComponent(dupeKey)}&limit=1`,
      ).catch(() => []);
      if (prior?.[0]?.property_id) {
        return json({
          ok: true,
          duplicate: true,
          property_id: prior[0].property_id,
          property_number: prior[0].property_number,
        }, 200);
      }
    }

    const insert: Record<string, unknown> = {
      title,
      property_type,
      address,
      price,
      area,
      description: str(body.description, 5000),
      room_type: str(body.room_type, 100),
      service_type: str(body.service_type, 50) ?? "Продава",
      neighborhood: str(body.neighborhood, 150),
      floor: num(body.floor),
      total_floors: num(body.total_floors),
      year_built: num(body.year_built),
      heating: str(body.heating, 100),
      cooling: bool(body.cooling),
      orientation: str(body.orientation, 100),
      parking: str(body.parking, 100),
      furnished: str(body.furnished, 100),
      garage: bool(body.garage),
      elevator: bool(body.elevator),
      yard: bool(body.yard),
      terrace: bool(body.terrace),
      basement: bool(body.basement),
      comments: str(body.comments, 5000),
      control_date: str(body.control_date, 50),
      available_from: str(body.available_from, 10),
      status: "active",
      is_published: typeof body.is_published === "boolean" ? body.is_published : false,
    };
    for (const k of Object.keys(insert)) if (insert[k] === undefined || insert[k] === null) delete insert[k];
    // price/area/title etc. already validated as present
    insert.title = title;
    insert.property_type = property_type;
    insert.address = address;
    insert.price = price;
    insert.area = area;

    const created = (await restPost("properties", insert))?.[0];
    if (!created?.id) throw new Error("property insert returned no row");

    // Owner contact
    let contact_id: string | null = null;
    const ownerPhone = str(body.owner_phone ?? body.contact?.phone, 50);
    if (ownerPhone) {
      const contact = (await restPost("property_contacts", {
        property_id: created.id,
        client_name: str(body.owner_name ?? body.contact?.name, 150),
        client_surname: str(body.owner_surname ?? body.contact?.surname, 150),
        client_phone: normalizePhone(ownerPhone) ?? ownerPhone,
        client_email: str(body.owner_email ?? body.contact?.email, 200),
        broker_name: str(body.broker_name, 150),
        owner_comments: str(body.owner_comments, 2000),
        is_primary: true,
      }))?.[0];
      contact_id = contact?.id ?? null;
    }

    // Images (already-hosted URLs scraped by Hermes)
    const images: Img[] = Array.isArray(body.images)
      ? body.images
          .map((im: any, i: number) =>
            typeof im === "string"
              ? { image_url: im, is_front_image: i === 0, display_order: i }
              : im?.image_url
              ? {
                  image_url: String(im.image_url),
                  is_front_image: im.is_front_image === true || i === 0,
                  display_order: Number.isFinite(im.display_order) ? im.display_order : i,
                }
              : null
          )
          .filter(Boolean)
          .slice(0, 40)
      : [];

    let inserted_images = 0;
    if (images.length) {
      const rows = await restPost(
        "property_images",
        images.map((im) => ({ ...im, property_id: created.id })),
      ).catch((e) => {
        console.error("image insert failed", e);
        return [];
      });
      inserted_images = rows?.length ?? 0;
      const front = rows?.find((r: any) => r.is_front_image) ?? rows?.[0];
      if (front?.id) {
        await restPatch("properties", `id=eq.${encodeURIComponent(created.id)}`, {
          front_image_id: front.id,
        }).catch((e) => console.error("front image link failed", e));
      }
    }

    await logEvent({
      event_type: "property.create",
      status: "processed",
      property_id: created.id,
      property_number: created.property_number,
      request_id: requestId,
      key_label: key.label,
      payload: body,
      result: { contact_id, images: inserted_images },
    });

    return json({
      ok: true,
      property_id: created.id,
      property_number: created.property_number,
      contact_id,
      images: inserted_images,
      is_published: created.is_published,
    }, 201);
  } catch (e) {
    console.error("create-property error", e);
    await logEvent({
      event_type: "property.create",
      status: "failed",
      request_id: requestId,
      key_label: key.label,
      payload: body,
      error_message: e instanceof Error ? e.message.slice(0, 500) : "unknown error",
    });
    return json({ error: "internal error" }, 500);
  }
});
